# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 86796f4623b81b62f3ce97886b52ba8551304a29959c3d0cc81b831254ead72cca94485d56a81d7adee6adb5b82632ba5f3f50f425417b8a8f1fa241d678fbe1

test:
  secret_key_base: 749cf0189d9d583fe7302eb27a8673f666986f275bc2dfa989c29fd877a0d344ccd6cc2b1cf980e1385cba0ca60eced17ce763ae147534032fd86d3cbf357ac3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
